name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Set up Gon
        run: brew install Bearer/tap/gon
      - name: Import Keychain Certs
        env: 
          P12_BASE64: ${{ secrets.CERTIFICATES_P12 }}
          P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        run: |
          # Create a temporary keychain
          keychain_path=$RUNNER_TEMP/app-signing.keychain-db
          keychain_password=$(openssl rand -base64 32)

          security create-keychain -p "$keychain_password" $keychain_path
          security set-keychain-settings -lut 21600 $keychain_path
          security unlock-keychain -p "$keychain_password" $keychain_path

          # Import certificate
          echo "$P12_BASE64" | base64 --decode > $RUNNER_TEMP/certificate.p12
          security import $RUNNER_TEMP/certificate.p12 -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $keychain_path
          security list-keychains -d user -s $keychain_path
      - name: Verify Identities
        run: security find-identity -v
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
